name: greengrocer_virtual
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  path_provider: ^2.1.3
  mask_text_input_formatter: ^2.9.0
  intl: ^0.19.0
  validatorless: ^1.2.3
  qr_flutter: ^4.1.0
  add_to_cart_animation: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Akshar
      fonts:
        - asset: assets/fonts/Akshar.ttf
    - family: AnekDevanagari
      fonts:
        - asset: assets/fonts/AnekDevanagari.ttf
